"""Two-agent competitive grid world - the live RL environment (Gymnasium API).

A navigate-to-goal gridworld: each agent heads from its spawn to the goal tile;
first one there WINS, a simultaneous arrival is a DRAW. Slippery junctions add a
stochastic transition model.

This subclasses ``gymnasium.Env`` to "capture" the Gymnasium concept, but it is a
two-agent env (PettingZoo-style): ``step`` takes a pair of actions and returns
per-agent obs/reward. The world is procedurally generated by ``worldgen`` and a
fresh one is installed on ``reset(regenerate=True)`` (what pressing R triggers).

Coordinates are (row, col); the theme camera flips the view, so the goal reads
top-centre and the spawns bottom-left/right on screen.
"""

import random

import gymnasium as gym
from gymnasium import spaces

import worldgen
from worldgen import WALL

# --- actions: N, S, W, E ----------------------------------------------------
ACTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1)]
N_ACTIONS = len(ACTIONS)
MOVE_ACTIONS = (0, 1, 2, 3)
# on a slippery tile a move may slide to a PERPENDICULAR direction: N/S slip to
# W/E, W/E slip to N/S (Benny's slippery/windy gridworld). This is the stochastic
# part of the otherwise-known transition model that Dynamic Programming solves.
PERP = {0: (2, 3), 1: (2, 3), 2: (0, 1), 3: (0, 1)}

# --- reward shaping ---------------------------------------------------------
STEP_COST = 0.01
WIN = 1.0
LOSE = -1.0
MAX_STEPS = 400

# Difference-of-potentials shaping: F = Φ(s') − Φ(s), with Φ = −W·(remaining path
# length to the goal). Progress earns +W, standing still 0, backtracking −W - a
# DENSE signal that speeds up the TD methods and makes Monte-Carlo (which can't
# bootstrap) viable.
#
# NOTE: we deliberately use Φ'−Φ, NOT the discounted γΦ'−Φ. The discounted form
# makes standing still pay (γ−1)·Φ > 0 - a "survival bonus" that grows with
# distance from the goal - so agents learn to dawdle. The difference form gives
# zero for no-progress and cannot be farmed. W is kept small so shaping never
# dwarfs the actual win.
SHAPE_W = 0.02
_UNREACH = 999


class GridWorld(gym.Env):
    metadata = {"render_modes": []}

    def __init__(self, seed=None, round_id=1, slip_ctrl=0.25):
        super().__init__()
        self._seed = seed
        self.round_id = round_id
        self.max_steps = MAX_STEPS      # per-episode step cap (tunable from the panel)
        # chance an agent LOSES CONTROL on a slippery junction.
        # 0 -> deterministic, 0.25 -> the classic 75/12.5/12.5 model. Panel-driven.
        self.slip_ctrl = max(0.0, min(0.9, float(slip_ctrl)))
        self.world = None
        self.rng = random.Random(seed)   # the ENVIRONMENT's own stochasticity (slips)
        self.action_space = spaces.Discrete(N_ACTIONS)
        self.n_actions = N_ACTIONS        # match.py reads this off the env
        self._install(worldgen.generate(seed, round_id))

    # ---------------------------------------------------------------- install
    def _install(self, world):
        self.world = world
        self.objective = getattr(world, "objective", "cross")
        self.goal_set = {tuple(e) for e in world.escape}
        g = world.grid
        self.H, self.W = world.H, world.W
        # every non-wall cell is a graph node
        self.floor_cells = [(r, c) for r in range(self.H) for c in range(self.W)
                            if g[r][c] != WALL]
        self.cell_index = {cell: i for i, cell in enumerate(self.floor_cells)}
        self.n_cells = len(self.floor_cells)
        # the observation is simply the agent's cell index (a single-agent navigator)
        self.observation_space = spaces.MultiDiscrete([self.n_cells])
        # slippery tiles (WHICH cells slip). The slip PROBABILITY is the env-level
        # slip_ctrl (panel-driven), shared by move_dist + _cross_move so the DP
        # model and the live dynamics stay identical.
        self.slip_set = {tuple(c) for c in world.slip_cells}
        # reward-shaping weight for THIS round (a world may set 0 for sparse rewards)
        ws = getattr(world, "shape_w", None)
        self.shape_w = SHAPE_W if ws is None else float(ws)
        self._build_distance_maps()

    # ----------------------------------------------------- shaping distances
    def _static_passable(self, agent, r, c):
        """Passability for the STATIC shaping / DP distance model: in-bounds and not
        a wall. ``agent`` is accepted for interface symmetry with the live rule (the
        DP planner passes this as its transition model)."""
        return 0 <= r < self.H and 0 <= c < self.W and self.world.grid[r][c] != WALL

    def _bfs_from(self, sources):
        from collections import deque
        dist = {s: 0 for s in sources}
        q = deque(sources)
        while q:
            r, c = q.popleft()
            for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                nr, nc = r + dr, c + dc
                if not self._static_passable(None, nr, nc) or (nr, nc) in dist:
                    continue
                dist[(nr, nc)] = dist[(r, c)] + 1
                q.append((nr, nc))
        return dist

    def _build_distance_maps(self):
        # shortest-path distance from every cell to the nearest goal tile; drives the
        # shaping potential. Both agents share it (no per-agent passability).
        self.dist_escape = self._bfs_from(list(self.world.escape))

    def _potential(self, agent):
        """Φ(s) = −W · remaining path length to the goal (W=0 on a sparse round)."""
        pos = self.red_pos if agent == "red" else self.blue_pos
        return -self.shape_w * self.dist_escape.get(pos, _UNREACH)

    # ------------------------------------------------------------------ tiles
    def passable(self, agent, r, c):
        # live passability: in-bounds and not a wall (a cross world has no doors).
        # ``agent`` is accepted for interface symmetry with _static_passable.
        return 0 <= r < self.H and 0 <= c < self.W and self.world.grid[r][c] != WALL

    # ------------------------------------------------------------------ reset
    def reset(self, *, seed=None, options=None, regenerate=False):
        if seed is not None:
            # reseed the slip RNG too, so a given seed fully reproduces the run
            self.rng = random.Random(seed)
        if regenerate or self.world is None:
            self._install(worldgen.generate(seed if seed is not None else self._seed,
                                            self.round_id))
        self.red_pos = self.world.red_spawn
        self.blue_pos = self.world.blue_spawn
        self.steps = 0
        self.done = False
        self.winner = None
        # per-episode reward decomposition (terminal / shaping / other) per agent
        self.ep_parts = {"red": {"terminal": 0.0, "shape": 0.0, "other": 0.0},
                         "blue": {"terminal": 0.0, "shape": 0.0, "other": 0.0}}
        obs = (self.observe("red"), self.observe("blue"))
        return obs, {}

    def _accum_parts(self, reward, shape, terminal):
        """Fold this step's reward into the per-episode decomposition: terminal
        (win/lose), shaping (Φ' - Φ), and other (step cost + penalties)."""
        for a in ("red", "blue"):
            p = self.ep_parts[a]
            s, t = shape.get(a, 0.0), terminal.get(a, 0.0)
            p["shape"] += s
            p["terminal"] += t
            p["other"] += reward[a] - s - t

    # ------------------------------------------------------------ observation
    def observe(self, agent):
        # each agent is an independent single-agent navigator; its state is simply
        # its cell index (a 1-tuple, so it stays a stable Q-table key).
        pos = self.red_pos if agent == "red" else self.blue_pos
        return (self.cell_index[pos],)

    # ------------------------------------------------------------------- step
    def _pos(self, agent):
        return self.red_pos if agent == "red" else self.blue_pos

    def _resolve(self, agent, pos, direction, passable=None):
        """Deterministic landing cell for one move DIRECTION (0..3) from pos.
        ``passable`` defaults to the live rule; the DP planner passes
        ``_static_passable`` so its model matches the shaping map."""
        passable = passable or self.passable
        dr, dc = ACTIONS[direction]
        nr, nc = pos[0] + dr, pos[1] + dc
        return (nr, nc) if passable(agent, nr, nc) else pos

    def move_dist(self, agent, pos, action, passable=None):
        """P(next cell | pos, action) - the KNOWN transition model. Deterministic
        everywhere except on a slippery tile, where the intended move slips to a
        perpendicular direction with probability ``slip_ctrl`` (split evenly). This
        is EXACTLY the model the live env samples in ``_cross_move``, so the DP
        planner solves the same MDP the game runs. Returns a list of (prob, cell);
        non-move actions stay put."""
        if action not in MOVE_ACTIONS:
            return [(1.0, pos)]
        p = self.slip_ctrl
        if pos not in self.slip_set or p <= 0.0:
            return [(1.0, self._resolve(agent, pos, action, passable))]
        outcomes = ((action, 1.0 - p), (PERP[action][0], p / 2.0), (PERP[action][1], p / 2.0))
        agg = {}
        for direction, prob in outcomes:
            cell = self._resolve(agent, pos, direction, passable)
            agg[cell] = agg.get(cell, 0.0) + prob
        return [(prob, cell) for cell, prob in agg.items()]

    def effective_actions(self, agent, pos=None):
        """Boolean mask over the action space: which actions actually DO something
        from ``pos`` (default: the agent's CURRENT cell). A move counts only if it
        does NOT bump a wall (it lands on a different cell). Action selection masks
        to these so a greedy policy can never self-loop on a wall - the agent makes
        a real move every tick. Never returns an all-False mask (a boxed-in agent,
        which shouldn't occur, falls back to all). Also used by the policy overlay
        so its arrows match the action the agent would actually take."""
        if pos is None:
            pos = self.red_pos if agent == "red" else self.blue_pos
        mask = [False] * self.n_actions
        for a in MOVE_ACTIONS:
            if self._resolve(agent, pos, a) != pos:
                mask[a] = True
        if not any(mask):
            mask = [True] * self.n_actions
        return mask

    def _cross_move(self, agent, pos, action):
        """Maze transition. On a normal cell the move is deterministic. On a
        SLIPPERY junction the agent's CHOSEN move slips to a perpendicular
        direction with probability ``slip_ctrl`` (the classic windy/slippery
        gridworld: intended w.p. 1-slip, each perpendicular w.p. slip/2), and if
        the slipped direction hits a wall it stays put. Perturbing the chosen
        action (not shoving toward a privileged best direction) makes the agent's
        own policy matter at the junction and keeps this identical to
        ``move_dist`` - so the DP planner and the live env solve the same MDP."""
        if action not in MOVE_ACTIONS:
            return pos
        if pos not in self.slip_set or self.slip_ctrl <= 0.0:
            return self._resolve(agent, pos, action)
        s = self.slip_ctrl
        roll = self.rng.random()
        if roll < 1.0 - s:
            d = action
        elif roll < 1.0 - s + s / 2.0:
            d = PERP[action][0]
        else:
            d = PERP[action][1]
        return self._resolve(agent, pos, d)      # _resolve stays put if blocked

    def step(self, a_red, a_blue):
        """One step: both agents move; first onto a goal cell wins, a simultaneous
        arrival is a draw."""
        if self.done:
            raise RuntimeError("step() on a finished episode")
        self.steps += 1
        reward = {"red": -STEP_COST, "blue": -STEP_COST}
        phi0 = {"red": self._potential("red"), "blue": self._potential("blue")}

        self.red_pos = self._cross_move("red", self.red_pos, a_red)
        self.blue_pos = self._cross_move("blue", self.blue_pos, a_blue)

        # reach the goal -> win; both crossing on the SAME step is a genuine DRAW
        # (equidistant spawns make a symmetric deterministic race tie every time).
        terminal = {"red": 0.0, "blue": 0.0}
        reached = [a for a in ("red", "blue") if self._pos(a) in self.goal_set]
        if reached:
            self.done = True
            if len(reached) == 2:
                self.winner = None
                terminal["red"] = terminal["blue"] = WIN
            else:
                self.winner = reached[0]
                loser = "blue" if self.winner == "red" else "red"
                terminal[self.winner] = WIN
                terminal[loser] = LOSE
            reward["red"] += terminal["red"]
            reward["blue"] += terminal["blue"]

        shape = {}
        for agent in ("red", "blue"):
            s = self._potential(agent) - phi0[agent]
            shape[agent] = s
            reward[agent] += s
        self._accum_parts(reward, shape, terminal)

        truncated = False
        if not self.done and self.steps >= self.max_steps:
            self.done = True
            truncated = True
            self.winner = None
        obs = (self.observe("red"), self.observe("blue"))
        return obs, reward, self.done, truncated, {"winner": self.winner}

    def to_json(self):
        """World descriptor for the viewer (/api/world). Grid rounds delegate to
        the generated World; the continuous round has its own descriptor."""
        return self.world.to_json()

    # --------------------------------------------------------------- snapshot
    def snapshot(self):
        """Live render state for the viewer: the two agents' cells, the step count,
        and the winner (None until someone reaches the goal)."""
        return {
            "red": list(self.red_pos), "blue": list(self.blue_pos),
            "steps": self.steps, "winner": self.winner,
        }


if __name__ == "__main__":
    env = GridWorld(seed=1)
    env.reset()
    print(f"World OK: {env.H}x{env.W}, {env.n_cells} walkable cells.")
    print(f"  obs(red) = {env.observe('red')}")
