"""Two-agent competitive grid world - the live RL environment (Gymnasium API).

Both agents have the IDENTICAL task and compete on it:
  1. pick up YOUR colored key (in your sealed bedroom; the room's door is locked
     until you hold it - the two bedrooms are sealed so colored keys can't be
     stolen),
  2. leave into the shared ARENA up north,
  3. grab the single GOLD key (the only stealable one - step onto the holder to
     take it),
  4. reach the north ESCAPE gate holding the gold key. First one out WINS.

This subclasses ``gymnasium.Env`` to "capture" the Gymnasium concept, but it is a
two-agent env (PettingZoo-style): ``step`` takes a pair of actions and returns
per-agent obs/reward. The world is procedurally generated by ``worldgen`` and a
fresh one is installed on ``reset(regenerate=True)`` (what pressing R triggers).

Mechanics beyond the core race (teleporter mirrors, lever+trap, ladders) are
layered on in a later phase; the observation tuple already reserves slots for
them so the agent's state signature won't change when they arrive.

Coordinates are (row, col), row 0 = NORTH (escape), row 19 = SOUTH (bedrooms).
"""

import random

import gymnasium as gym
from gymnasium import spaces

import worldgen
from worldgen import (
    WALL, RED_DOOR, BLUE_DOOR, RED_KEY, BLUE_KEY,
)

# --- actions: N, S, W, E, USE (USE is a no-op until levers exist) -----------
ACTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1), (0, 0)]
USE = 4
N_ACTIONS = len(ACTIONS)
MOVE_ACTIONS = (0, 1, 2, 3)
# on a slippery tile a move may slide to a PERPENDICULAR direction: N/S slip to
# W/E, W/E slip to N/S (Benny's slippery/windy gridworld). This is the stochastic
# part of the otherwise-known transition model that Dynamic Programming solves.
PERP = {0: (2, 3), 1: (2, 3), 2: (0, 1), 3: (0, 1)}
# turns relative to a facing direction (0=N, 1=S, 2=W, 3=E), for the maze's
# "lose control on a slippery junction" transition model (see _cross_move).
LEFT_OF = {0: 2, 1: 3, 2: 1, 3: 0}
RIGHT_OF = {0: 3, 1: 2, 2: 0, 3: 1}
BACK_OF = {0: 1, 1: 0, 2: 3, 3: 2}

# --- coarse opponent regions ------------------------------------------------
REGION_RED, REGION_BLUE, REGION_ARENA = 0, 1, 2
N_REGIONS = 3

# --- gold-key location categories (for the per-agent observation) -----------
GOLD_GROUND, GOLD_MIRROR_A, GOLD_MIRROR_B, GOLD_RIVAL, GOLD_ME = 0, 1, 2, 3, 4
N_GOLD_LOC = 5

# --- reward shaping ---------------------------------------------------------
STEP_COST = 0.01
KEY_BONUS = 0.10
GOLD_BONUS = 0.30
WIN = 1.0
LOSE = -1.0
MAX_STEPS = 400
TRAP_PENALTY = -0.05   # being snared (the big cost is being flung back to spawn)
TRAP_REWARD = 0.05     # for the agent whose armed trap caught the rival
CLIFF_PENALTY = -0.5   # "cross" worlds: fall into an open manhole, then respawn

# Difference-of-potentials shaping: F = Φ(s') − Φ(s), with Φ = −W·(remaining path
# length to the goal through the required sub-goals). Progress earns +W, standing
# still 0, backtracking −W - a DENSE signal so the long key→gold→escape chain is
# learnable without first completing it by luck (this is what makes Monte-Carlo,
# which can't bootstrap, viable here, and it speeds up the TD methods too).
#
# NOTE: we deliberately use Φ'−Φ, NOT the discounted γΦ'−Φ. The discounted form
# makes standing still pay (γ−1)·Φ > 0 - a "survival bonus" that grows with
# distance from the goal - so agents learn to dawdle. The difference form gives
# zero for no-progress and cannot be farmed. W is kept small so shaping never
# dwarfs the actual win.
SHAPE_W = 0.02
_UNREACH = 999


class GridWorld(gym.Env):
    metadata = {"render_modes": []}

    def __init__(self, seed=None, round_id=1, slip_ctrl=0.25):
        super().__init__()
        self._seed = seed
        self.round_id = round_id
        self.max_steps = MAX_STEPS      # per-episode step cap (tunable from the panel)
        # chance an agent LOSES CONTROL on a slippery junction (cross rounds).
        # 0 -> deterministic, 0.25 -> the classic 75/10/10/5 model. Panel-driven.
        self.slip_ctrl = max(0.0, min(0.9, float(slip_ctrl)))
        self.world = None
        self.rng = random.Random(seed)   # the ENVIRONMENT's own stochasticity (slips)
        self.action_space = spaces.Discrete(N_ACTIONS)
        self.n_actions = N_ACTIONS        # match.py reads this off the env (grid=5)
        # obs: (cell index, own-key, gold loc, opp region, opp adjacent, trap armed)
        self._install(worldgen.generate(seed, round_id))

    # ---------------------------------------------------------------- install
    def _install(self, world):
        self.world = world
        # "race" (key->gold->escape) vs "cross" (Cliff Walking: start->goal over a
        # manhole cliff). Set early - the shaping BFS below branches on it.
        self.objective = getattr(world, "objective", "race")
        self.goal_set = {tuple(e) for e in world.escape}
        g = world.grid
        self.H, self.W = world.H, world.W
        # every non-wall cell is a graph node (doors included - passability is
        # checked per step). Verticality (phase 4) will append catwalk nodes.
        self.floor_cells = [(r, c) for r in range(self.H) for c in range(self.W)
                            if g[r][c] != WALL]
        self.cell_index = {cell: i for i, cell in enumerate(self.floor_cells)}
        self.n_cells = len(self.floor_cells)
        self.observation_space = spaces.MultiDiscrete(
            [self.n_cells, 2, N_GOLD_LOC, N_REGIONS, 2, 2])
        # mechanics lookups
        self.mirror_map = {}
        for a, b in world.mirrors:
            self.mirror_map[tuple(a)] = tuple(b)
            self.mirror_map[tuple(b)] = tuple(a)
        self.lever_set = {tuple(c) for c in world.levers}
        self.trap_set = {tuple(c) for c in world.traps}
        self.drop_set = {tuple(c) for c in world.drop_traps}
        # slippery tiles + slip probability (the known stochastic transition model)
        self.slip_set = {tuple(c) for c in world.slip_cells}
        self.slip_prob = float(getattr(world, "slip_prob", 0.0) or 0.0)
        # ladders: a climb edge A<->B over an intervening wall. ladder_adj feeds
        # the shaping BFS; climb_map resolves "walk into the laddered wall -> hop
        # to the far side" during a move.
        self.ladder_adj = {}
        self.climb_map = {}
        for a, b in world.ladders:
            a, b = tuple(a), tuple(b)
            self.ladder_adj.setdefault(a, []).append(b)
            self.ladder_adj.setdefault(b, []).append(a)
            self.climb_map[(a, self._dir_action(a, b))] = b
            self.climb_map[(b, self._dir_action(b, a))] = a
        self._build_distance_maps()

    @staticmethod
    def _dir_action(frm, to):
        dr = (to[0] > frm[0]) - (to[0] < frm[0])
        dc = (to[1] > frm[1]) - (to[1] < frm[1])
        return ACTIONS.index((dr, dc))

    # ----------------------------------------------------- shaping distances
    def _static_passable(self, agent, r, c):
        """Passability for the STATIC distance maps: an agent's OWN door counts as
        open (it will hold the key when it crosses), the rival's door as shut."""
        if not (0 <= r < self.H and 0 <= c < self.W):
            return False
        t = self.world.grid[r][c]
        if t == WALL:
            return False
        # cross worlds: the shaping potential routes AROUND the manholes (so the
        # cautious detour reads as "making progress"); falling in is steppable but
        # handled as a live penalty, not a static path.
        if self.objective == "cross" and (r, c) in self.drop_set:
            return False
        if t == RED_DOOR:
            return agent == "red"
        if t == BLUE_DOOR:
            return agent == "blue"
        return True

    def _bfs_from(self, sources, agent):
        from collections import deque
        dist = {s: 0 for s in sources}
        q = deque(sources)
        while q:
            r, c = q.popleft()
            for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                nr, nc = r + dr, c + dc
                if not self._static_passable(agent, nr, nc):
                    continue
                # stepping onto a mirror pad lands you on its partner - so the
                # shaping potential is aware of the teleport shortcut
                arrive = self.mirror_map.get((nr, nc), (nr, nc))
                if arrive in dist:
                    continue
                dist[arrive] = dist[(r, c)] + 1
                q.append(arrive)
            # ladder climbs are extra edges over the walls
            for to in self.ladder_adj.get((r, c), ()):
                if to not in dist:
                    dist[to] = dist[(r, c)] + 1
                    q.append(to)
        return dist

    def _build_distance_maps(self):
        w = self.world
        self.dist_key, self.dist_gold, self.dist_escape = {}, {}, {}
        self.d_key_gold, self.d_gold_escape = {}, {}
        for agent, own_key in (("red", w.red_key), ("blue", w.blue_key)):
            self.dist_key[agent] = self._bfs_from([own_key], agent)
            self.dist_gold[agent] = self._bfs_from([w.gold_home], agent)
            self.dist_escape[agent] = self._bfs_from(list(w.escape), agent)
            self.d_key_gold[agent] = self.dist_gold[agent].get(own_key, _UNREACH)
            self.d_gold_escape[agent] = self.dist_escape[agent].get(w.gold_home, _UNREACH)

    def _potential(self, agent):
        """Φ(s) = −W · remaining path length to escape through the needed sub-goals."""
        if self.objective == "cross":
            # straight-line-ish progress toward the goal, routed around the manholes
            pos = self.red_pos if agent == "red" else self.blue_pos
            return -SHAPE_W * self.dist_escape[agent].get(pos, _UNREACH)
        if agent == "red":
            pos, has_key = self.red_pos, self.red_key
        else:
            pos, has_key = self.blue_pos, self.blue_key
        holds_gold = self.gold_holder == agent
        if holds_gold or self.gold_holder is not None:
            # I have the gold (head to escape), or the rival has it (post toward exit)
            remaining = self.dist_escape[agent].get(pos, _UNREACH)
        elif has_key:
            remaining = self.dist_gold[agent].get(pos, _UNREACH) + self.d_gold_escape[agent]
        else:
            remaining = (self.dist_key[agent].get(pos, _UNREACH)
                         + self.d_key_gold[agent] + self.d_gold_escape[agent])
        return -SHAPE_W * remaining

    @property
    def state_space_size(self):
        return self.n_cells * 2 * N_GOLD_LOC * N_REGIONS * 2 * 2

    # ------------------------------------------------------------------ tiles
    def region_of(self, r, c):
        if r <= 12:
            return REGION_ARENA          # rows 0-12 = the shared dining hall
        return REGION_RED if c <= 9 else REGION_BLUE

    def passable(self, agent, r, c):
        if not (0 <= r < self.H and 0 <= c < self.W):
            return False
        t = self.world.grid[r][c]
        if t == WALL:
            return False
        if t == RED_DOOR:
            return agent == "red" and self.red_key
        if t == BLUE_DOOR:
            return agent == "blue" and self.blue_key
        return True

    # ------------------------------------------------------------------ reset
    def set_round(self, round_id):
        """Switch the active round and install its world (used by the tournament)."""
        self.round_id = round_id
        self._install(worldgen.generate(self._seed, round_id))

    def reset(self, *, seed=None, options=None, regenerate=False):
        if regenerate or self.world is None:
            self._install(worldgen.generate(seed if seed is not None else self._seed,
                                            self.round_id))
        self.red_pos = self.world.red_spawn
        self.blue_pos = self.world.blue_spawn
        self.red_key = False
        self.blue_key = False
        self.gold_holder = None
        self.gold_pos = self.world.gold_home
        self.red_got_gold = False
        self.blue_got_gold = False
        self.trap_armed = False
        self.steps = 0
        self.done = False
        self.winner = None
        # cross worlds: latched fall events (count + where) so the 30Hz viewer
        # never misses a manhole drop even when the sim steps faster than it polls
        self.fall_n = {"red": 0, "blue": 0}
        self.fall_cell = {"red": None, "blue": None}
        # per-episode reward decomposition (terminal / shaping / other) per agent
        self.ep_parts = {"red": {"terminal": 0.0, "shape": 0.0, "other": 0.0},
                         "blue": {"terminal": 0.0, "shape": 0.0, "other": 0.0}}
        obs = (self.observe("red"), self.observe("blue"))
        return obs, {}

    def _accum_parts(self, reward, shape, terminal):
        """Fold this step's reward into the per-episode decomposition: terminal
        (win/lose), shaping (Φ' - Φ), and other (step cost + bonuses + penalties)."""
        for a in ("red", "blue"):
            p = self.ep_parts[a]
            s, t = shape.get(a, 0.0), terminal.get(a, 0.0)
            p["shape"] += s
            p["terminal"] += t
            p["other"] += reward[a] - s - t

    # ------------------------------------------------------------ observation
    def _gold_loc(self, agent):
        if self.gold_holder == agent:
            return GOLD_ME
        if self.gold_holder is not None:
            return GOLD_RIVAL
        return GOLD_GROUND  # phase 4 will distinguish mirror-target cells

    def observe(self, agent):
        if agent == "red":
            pos, has_key, other = self.red_pos, self.red_key, self.blue_pos
        else:
            pos, has_key, other = self.blue_pos, self.blue_key, self.red_pos
        if self.objective == "cross":
            # Cliff Walking: each agent is an independent single-agent learner whose
            # state is simply its cell (no opponent context -> no aliasing, clean
            # greedy policy). The two just happen to share the map.
            return (self.cell_index[pos], 0, GOLD_GROUND, REGION_ARENA, 0, 0)
        opp_region = self.region_of(*other)
        adj = 1 if (abs(pos[0] - other[0]) + abs(pos[1] - other[1])) <= 1 else 0
        return (self.cell_index[pos], int(has_key), self._gold_loc(agent),
                opp_region, adj, int(self.trap_armed))

    # ------------------------------------------------------------------- step
    def _pos(self, agent):
        return self.red_pos if agent == "red" else self.blue_pos

    def _resolve(self, agent, pos, direction, passable=None):
        """Deterministic landing cell for one move DIRECTION (0..3) from pos.
        ``passable`` defaults to the live rule; the DP planner passes
        ``_static_passable`` so its model doesn't depend on live key state."""
        passable = passable or self.passable
        dr, dc = ACTIONS[direction]
        nr, nc = pos[0] + dr, pos[1] + dc
        if passable(agent, nr, nc):
            npos = (nr, nc)
            # teleporter mirrors warp you to the paired pad
            return self.mirror_map.get(npos, npos)
        # blocked by a wall - but a ladder may climb over THIS wall to the far side
        return self.climb_map.get((pos, direction), pos)

    def move_dist(self, agent, pos, action, passable=None):
        """P(next cell | pos, action) - the KNOWN transition model. Deterministic
        everywhere except on a slippery tile, where the move slides to a
        perpendicular direction with probability ``slip_prob`` (split evenly).
        Returns a list of (prob, cell). USE / non-moves stay put."""
        if action not in MOVE_ACTIONS:
            return [(1.0, pos)]
        if pos not in self.slip_set or self.slip_prob <= 0.0:
            return [(1.0, self._resolve(agent, pos, action, passable))]
        p = self.slip_prob
        outcomes = ((action, 1.0 - p), (PERP[action][0], p / 2.0), (PERP[action][1], p / 2.0))
        agg = {}
        for direction, prob in outcomes:
            cell = self._resolve(agent, pos, direction, passable)
            agg[cell] = agg.get(cell, 0.0) + prob
        return [(prob, cell) for cell, prob in agg.items()]

    def _move(self, agent, pos, action):
        dist = self.move_dist(agent, pos, action)
        if len(dist) == 1:
            return dist[0][1]
        roll, acc = self.rng.random(), 0.0
        for prob, cell in dist:
            acc += prob
            if roll <= acc:
                return cell
        return dist[-1][1]

    def _best_dir(self, agent, pos):
        """The optimal move direction toward the goal from pos - the env's
        privileged knowledge, read off the precomputed escape-distance map."""
        dist = self.dist_escape[agent]
        best_a, best_d = None, _UNREACH + 1
        for a in MOVE_ACTIONS:
            nxt = self._resolve(agent, pos, a)
            if nxt == pos:                       # blocked / no progress
                continue
            d = dist.get(nxt, _UNREACH)
            if d < best_d:
                best_d, best_a = d, a
        return best_a if best_a is not None else 0

    def _cross_move(self, agent, pos, action):
        """Maze transition. On a normal cell the move is deterministic. On a
        SLIPPERY junction the agent loses control with probability ``slip_ctrl``
        (default 0.25 = the classic 75/10/10/5 model): it's shoved the BEST way
        (the optimal direction only the env knows) most of the time, else
        left / right / backward of that - and if the shoved direction hits a bush
        it stays put. That makes risky junctions dangerous but still learnable."""
        if action not in MOVE_ACTIONS:
            return pos
        if pos not in self.slip_set or self.slip_ctrl <= 0.0:
            return self._resolve(agent, pos, action)
        best = self._best_dir(agent, pos)
        # keep the classic 40/40/20 split of the lost-control mass across
        # left / right / backward, scaled by slip_ctrl.
        s = self.slip_ctrl
        roll = self.rng.random()
        if roll < 1.0 - s:
            d = best
        elif roll < 1.0 - s + 0.4 * s:
            d = LEFT_OF[best]
        elif roll < 1.0 - s + 0.8 * s:
            d = RIGHT_OF[best]
        else:
            d = BACK_OF[best]
        return self._resolve(agent, pos, d)      # _resolve stays put if blocked

    def _step_cross(self, a_red, a_blue):
        """Cliff-Walking step: both move; stepping onto an open manhole drops you
        (penalty + back to spawn); first onto a goal cell wins."""
        self.steps += 1
        reward = {"red": -STEP_COST, "blue": -STEP_COST}
        phi0 = {"red": self._potential("red"), "blue": self._potential("blue")}

        self.red_pos = self._cross_move("red", self.red_pos, a_red)
        self.blue_pos = self._cross_move("blue", self.blue_pos, a_blue)

        # fall into an open manhole -> penalty, then flung back to spawn
        for agent in ("red", "blue"):
            if self._pos(agent) in self.drop_set:
                reward[agent] += CLIFF_PENALTY
                self.fall_n[agent] += 1                       # latch for the viewer
                self.fall_cell[agent] = list(self._pos(agent))
                if agent == "red":
                    self.red_pos = self.world.red_spawn
                else:
                    self.blue_pos = self.world.blue_spawn

        # reach the goal -> win; both crossing on the SAME step is a genuine DRAW
        # (no silent default to red - Peach's spawns are equidistant, so a symmetric
        # deterministic race ties every time). Both are rewarded for arriving.
        terminal = {"red": 0.0, "blue": 0.0}
        reached = [a for a in ("red", "blue") if self._pos(a) in self.goal_set]
        if reached:
            self.done = True
            if len(reached) == 2:
                self.winner = None
                terminal["red"] = terminal["blue"] = WIN
            else:
                self.winner = reached[0]
                loser = "blue" if self.winner == "red" else "red"
                terminal[self.winner] = WIN
                terminal[loser] = LOSE
            reward["red"] += terminal["red"]
            reward["blue"] += terminal["blue"]

        shape = {}
        for agent in ("red", "blue"):
            s = self._potential(agent) - phi0[agent]
            shape[agent] = s
            reward[agent] += s
        self._accum_parts(reward, shape, terminal)

        truncated = False
        if not self.done and self.steps >= self.max_steps:
            self.done = True
            truncated = True
            self.winner = None
        obs = (self.observe("red"), self.observe("blue"))
        return obs, reward, self.done, truncated, {"winner": self.winner}

    def step(self, a_red, a_blue):
        if self.done:
            raise RuntimeError("step() on a finished episode")
        if self.objective == "cross":
            return self._step_cross(a_red, a_blue)
        self.steps += 1
        reward = {"red": -STEP_COST, "blue": -STEP_COST}
        phi0 = {"red": self._potential("red"), "blue": self._potential("blue")}

        # 1) both move simultaneously (co-occupancy allowed)
        self.red_pos = self._move("red", self.red_pos, a_red)
        self.blue_pos = self._move("blue", self.blue_pos, a_blue)

        # 2) colored keys (one-time, never contested - rooms are sealed)
        if not self.red_key and self.red_pos == self.world.red_key:
            self.red_key = True
            reward["red"] += KEY_BONUS
        if not self.blue_key and self.blue_pos == self.world.blue_key:
            self.blue_key = True
            reward["blue"] += KEY_BONUS

        # 3) gold key pickup / steal
        if self.gold_holder is None:
            on_red = self.red_pos == self.gold_pos
            on_blue = self.blue_pos == self.gold_pos
            if on_red or on_blue:
                self.gold_holder = "red" if on_red else "blue"   # tie -> red
                self.gold_pos = None
        else:
            holder = self.gold_holder
            thief = "blue" if holder == "red" else "red"
            if self._pos(thief) == self._pos(holder):
                self.gold_holder = thief                          # contact steal

        # one-time gold bonus
        if self.gold_holder == "red" and not self.red_got_gold:
            self.red_got_gold = True
            reward["red"] += GOLD_BONUS
        elif self.gold_holder == "blue" and not self.blue_got_gold:
            self.blue_got_gold = True
            reward["blue"] += GOLD_BONUS

        # 3b) drop-traps: carrying the gold onto one knocks it loose, and it
        #     warps back to its pedestal - a real setback for a careless carrier
        if self.gold_holder is not None and self._pos(self.gold_holder) in self.drop_set:
            reward[self.gold_holder] += TRAP_PENALTY
            self.gold_holder = None
            self.gold_pos = self.world.gold_home

        # 4) levers: USE while standing on a lever toggles the snare trap (both
        #    agents observe trap_armed, so this is a genuinely learned interaction)
        for agent, act in (("red", a_red), ("blue", a_blue)):
            if act == USE and self._pos(agent) in self.lever_set:
                self.trap_armed = not self.trap_armed

        # 5) trap: if armed, an agent on the trap cell is flung back to its spawn
        #    (a real setback, and it can snare YOU too). Resolved before escape so
        #    a trap can deny a gold-carrier right at the gate.
        if self.trap_armed:
            for agent in ("red", "blue"):
                if self._pos(agent) in self.trap_set:
                    if agent == "red":
                        self.red_pos = self.world.red_spawn
                    else:
                        self.blue_pos = self.world.blue_spawn
                    self.trap_armed = False
                    other = "blue" if agent == "red" else "red"
                    reward[agent] += TRAP_PENALTY
                    reward[other] += TRAP_REWARD
                    break

        # 6) escape: holding gold AND on the gate -> win
        terminal = {"red": 0.0, "blue": 0.0}
        for agent in ("red", "blue"):
            if self.gold_holder == agent and self._pos(agent) in self.world.escape:
                self.done = True
                self.winner = agent
                loser = "blue" if agent == "red" else "red"
                terminal[agent] = WIN
                terminal[loser] = LOSE
                reward[agent] += WIN
                reward[loser] += LOSE
                break

        # difference-of-potentials shaping: F = Φ(s') − Φ(s), added to each agent
        shape = {}
        for agent in ("red", "blue"):
            s = self._potential(agent) - phi0[agent]
            shape[agent] = s
            reward[agent] += s
        self._accum_parts(reward, shape, terminal)

        truncated = False
        if not self.done and self.steps >= self.max_steps:
            self.done = True
            truncated = True
            self.winner = None  # draw / timeout

        obs = (self.observe("red"), self.observe("blue"))
        return obs, reward, self.done, truncated, {"winner": self.winner}

    def to_json(self):
        """World descriptor for the viewer (/api/world). Grid rounds delegate to
        the generated World; the continuous round has its own descriptor."""
        return self.world.to_json()

    # --------------------------------------------------------------- snapshot
    def snapshot(self):
        """Live render state for the viewer (positions + key/gold flags)."""
        if self.objective == "cross":
            # no keys / gold in a cross world; flags set so the viewer hides them
            return {
                "red": list(self.red_pos), "blue": list(self.blue_pos),
                "redKey": True, "blueKey": True,
                "gold": {"holder": None, "pos": None},
                "trapArmed": False,
                "fell": {
                    "red": {"n": self.fall_n["red"], "cell": self.fall_cell["red"]},
                    "blue": {"n": self.fall_n["blue"], "cell": self.fall_cell["blue"]},
                },
                "steps": self.steps, "winner": self.winner,
            }
        if self.gold_holder is None:
            gold = {"holder": None, "pos": list(self.gold_pos)}
        else:
            gold = {"holder": self.gold_holder, "pos": None}
        return {
            "red": list(self.red_pos), "blue": list(self.blue_pos),
            "redKey": self.red_key, "blueKey": self.blue_key,
            "gold": gold, "trapArmed": self.trap_armed,
            "steps": self.steps, "winner": self.winner,
        }


if __name__ == "__main__":
    env = GridWorld(seed=1)
    env.reset()
    print(f"World OK: {env.H}x{env.W}, {env.n_cells} walkable cells.")
    print(f"  state space per agent ~= {env.state_space_size:,} x {N_ACTIONS} actions")
    print(f"  obs(red) = {env.observe('red')}")
